name: Trigger auto deployment for xiaoan-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/xiaoan-web-AutoDeployTrigger-644865fe-3cfb-4c0e-862f-3a6dad3e0586.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.XIAOANWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.XIAOANWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.XIAOANWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: xiaoanhd5dc8acr.azurecr.io
          registryUsername: ${{ secrets.XIAOANWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.XIAOANWEB_REGISTRY_PASSWORD }}
          containerAppName: xiaoan-web
          resourceGroup: xiaoan-pilot-rg
          imageToBuild: xiaoanhd5dc8acr.azurecr.io/xiaoan-web:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


